# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 450)
        MainWindow.setMinimumSize(QtCore.QSize(700, 450))
        MainWindow.setMaximumSize(QtCore.QSize(700, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(400, 10, 281, 171))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.btnRun = QtWidgets.QPushButton(self.groupBox)
        self.btnRun.setGeometry(QtCore.QRect(190, 130, 86, 27))
        self.btnRun.setObjectName("btnRun")
        self.btnStop = QtWidgets.QPushButton(self.groupBox)
        self.btnStop.setGeometry(QtCore.QRect(100, 130, 86, 27))
        self.btnStop.setObjectName("btnStop")
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        self.btnClear.setGeometry(QtCore.QRect(10, 130, 86, 27))
        self.btnClear.setObjectName("btnClear")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(200, 70, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(190, 30, 81, 31))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 181, 29))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 181, 29))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(399, 310, 281, 111))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnHelp = QtWidgets.QPushButton(self.groupBox_2)
        self.btnHelp.setGeometry(QtCore.QRect(150, 40, 86, 27))
        self.btnHelp.setObjectName("btnHelp")
        self.btnSite = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSite.setGeometry(QtCore.QRect(60, 40, 86, 27))
        self.btnSite.setObjectName("btnSite")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(100, 70, 81, 31))
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 371, 171))
        self.groupBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_3.setObjectName("groupBox_3")
        self.txtEvents = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtEvents.setGeometry(QtCore.QRect(10, 30, 351, 131))
        self.txtEvents.setObjectName("txtEvents")
        self.txtEvents.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 190, 371, 231))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtLogs = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtLogs.setGeometry(QtCore.QRect(10, 30, 351, 191))
        self.txtLogs.setObjectName("txtLogs")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 210, 281, 71))
        self.groupBox_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(180, 40, 81, 31))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.lblStatus = QtWidgets.QLabel(self.groupBox_5)
        self.lblStatus.setGeometry(QtCore.QRect(-10, 40, 171, 31))
        self.lblStatus.setObjectName("lblStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnRun.clicked.connect(self.btnRun.deleteLater)
        self.btnStop.clicked.connect(self.btnStop.deleteLater)
        self.btnClear.clicked.connect(self.btnClear.deleteLater)
        self.btnHelp.clicked.connect(self.btnHelp.deleteLater)
        self.btnSite.clicked.connect(self.btnSite.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "املاک یاب دیوار"))
        self.groupBox.setTitle(_translate("MainWindow", "بخش اجرایی"))
        self.btnRun.setText(_translate("MainWindow", "شروع"))
        self.btnStop.setText(_translate("MainWindow", "توقف"))
        self.btnClear.setText(_translate("MainWindow", "پاک کردن"))
        self.label_2.setText(_translate("MainWindow", "حداکثر اجاره :"))
        self.label.setText(_translate("MainWindow", "حداکثر ودیعه :"))
        self.groupBox_2.setTitle(_translate("MainWindow", "بخش توسعه"))
        self.btnHelp.setText(_translate("MainWindow", "راهنما"))
        self.btnSite.setText(_translate("MainWindow", "توسعه"))
        self.label_3.setText(_translate("MainWindow", "نسخه: 0.0.1"))
        self.groupBox_3.setTitle(_translate("MainWindow", "رخدادها"))
        self.groupBox_4.setTitle(_translate("MainWindow", "لاگ ها"))
        self.groupBox_5.setTitle(_translate("MainWindow", "بخش وضعیت"))
        self.label_4.setText(_translate("MainWindow", "نمایش وضعیت : "))
        self.lblStatus.setText(_translate("MainWindow", "خاموش"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
